### ISSUE TITLE
Rails 4 Support

### ISSUE THREAD

**Issue by DanielBlanco** [chamnap/active_record_uuid#1]
Hi! 

This gem depends on activerecord (~> 3.0) and Rails 4 depends on activerecord (4.0.0).

Did you test this gem in rails 4? does it work?

Thanks!

**Comment by chamnap** [comment]
Sorry, I'm too busy. I haven't checked it supports activerecord 4 or not.

**Comment by chamnap** [comment]
Now, it supports rails 4. @DanielBlanco, you can try out from the current master branch. Check out the build at https://travis-ci.org/chamnap/active_record_uuid.

**Comment by DanielBlanco** [comment]
ty :+1:
